
---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-kinoite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - fastfetch
        - distrobox

   # Install stuff from negativo
  - type: dnf
    repos:
      nonfree: negativo17
    replace:
      - from-repo: fedora-multimedia
        skip-unavailable: true
        packages:
          - libva
          - mesa-dri-drivers
          - mesa-filesystem
          - mesa-libEGL
          - mesa-libGL
          - mesa-libgbm
          - mesa-va-drivers
          - mesa-vulkan-drivers
          - libheif

  - type: dnf
    install:
      packages:
        - libopenjph # Manually install dependency for `libheif`, as Negativo upstreamed it
        - repo: fedora-multimedia
          packages:
            - libva-utils
            - pipewire-libs-extra
            - heif-pixbuf-loader
    replace:
      - from-repo: fedora-multimedia
        packages:
          - old: ffmpeg-free
            new: ffmpeg
          - old: libfdk-aac-free
            new: libfdk-aac
          - old: libavcodec-free
            new: libavcodec

  - type: dnf
    install:
      packages:
        - repo: fedora-multimedia
          packages:
            - ffmpeg-libs

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: brew
    nofile-limits: true          # increase nofile limits
    brew-analytics: false        # disable telemetry

  - type: default-flatpaks
    configurations:
      - notify: false            # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install:                # system flatpaks we want all users to have and not remove
        #  - org.mozilla.firefox

      - scope: user             # Also add Flathub user repo, but no user packages

  - type: signing               # this sets up the proper policy & signing files for signed images to work fully
